### ISSUE TITLE
Add a stopwatch that stops when you solve the puzzle

### ISSUE THREAD

**Issue by R1Vv** [chrisboyle/sgtpuzzles#576] opened 2022-12-22 03:32 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A clear and concise description of what you want to happen. A stopwatch, that you can optionally turn on, that when you solve the puzzle, stops, and is shown to you.

**Describe alternatives you've considered**

**Additional context**

**Comment by chrisboyle** [comment] 2022-12-22 17:00
Duplicate of #324

**Closed by chrisboyle** 2022-12-22 17:00 UTC
Labels: feature
