### ISSUE TITLE
Would you like to add the new game?

### ISSUE THREAD

**Issue by ejmoog** [chrisboyle/sgtpuzzles#514] opened 2022-03-18 15:20 UTC
Simon Tatham’s Portable Puzzle Collection had add a new game, there are 40 games in the official site.  Would you like to add the new game?

**Comment by chrisboyle** [comment] 2022-03-21 15:31
Duplicate of #488: yes, catching up with upstream is very much the plan, as and when I have time. (It's not a simple merge, there are ~3 years of changes to look through and the new game needs controls mapping etc.)

**Closed by chrisboyle** 2022-03-21 15:31 UTC
