### ISSUE TITLE
All games request

### ISSUE THREAD

**Issue by SherylK621** [chrisboyle/sgtpuzzles#579] opened 2022-12-30 05:47 UTC
I would prefer not to have errors turn red on all games until I'm done solving. For example, in Slant, I don't switch between left and right slant, I toggle thru to the one I want. I'd rather not know which is wrong until I'm ready to know. 

A 'show errors' feature would work here.

**Comment by chrisboyle** [comment] 2022-12-30 17:00
Thanks for your suggestion. This is a duplicate of #258 (and would need to be coordinated with Simon upstream; it's not something I would want as an Android-specific difference).

**Closed by chrisboyle** 2022-12-30 17:00 UTC
Labels: feature, upstream

**Comment by SherylK621** [comment] 2022-12-30 17:04
Got it - thanks Chris.
