### ISSUE TITLE
"Package file was not signed correctly" on Android 2.2 device

### ISSUE THREAD

**Issue by ylitvinenko** [chrisboyle/sgtpuzzles#403] opened 2016-09-12 09:07 UTC
I was trying to install Simon Tatham's Puzzles to one of my obsolete Android tablets which are technically compatible with the game. However, upon installing it from the Play Store, I've got a "Package file was not signed correctly" message.

I have downloaded the APK (ver. 2016-01-13-0847-1d9d6cb) from the official website, as well as 2015-09-10-2219-eda5a86 version from a third-party source. I wasn't able to install either of them.

My device is ZTE V9 (branded as MTS 1055 by the eponymous Russian carrier) flashed with its stock generic ROM (without carrier alterations). Here are additional details:
- Model number: Light
- Android version: 2.2
- Kernel version: 2.6.32.9-pref
- Build number: V9_GENERICV1.0.0B07
- The device is not rooted and has no other non-system/non-bundled apps

I'd like to know if the game is incompatible with Android 2.2 altogether (then the corresponding correction should be made on the web site and on the Play Store page), or is it just my device behaving weird. (I'd like to see the patch in the latter case, but I realise that it won't be practical to make one.)

**Comment by chrisboyle** [comment] 2016-09-12 10:19
Duplicate of #234: this is known but not specific to this application. It seems Android Studio produces APKs that hit this problem on Android 2.2 (but 2.1 is fine!) Note zvr's comment on #234 which suggests you may be able to work around this by re-signing it yourself with `jarsigner`, which I haven't tried. I am reluctant to do that myself for the published builds in case new devices (an obvious majority) might in some cases be incompatible with this old jarsigner method. I can't test every device and it seems Android Studio is the tried and tested method for modern devices.

**Closed by chrisboyle** 2016-09-12 10:19 UTC
