### ISSUE TITLE
Loopy, Palisade: change inactive line color

### ISSUE THREAD

**Issue by DAM091** [chrisboyle/sgtpuzzles#567] opened 2022-10-02 14:46 UTC
In both Loopy and Palisade, the inactive line is yellow. I find this very difficult to see over the gray background, even with the brightness maxed. I always need to switch to night mode on these puzzles. Could the color be changed to something that contrasts better? Or could the option be given to choose my own color?

Honestly, I don't have any desire to pick my own color, so long as it's a more visible one. But, I realize that you can't please everybody, so maybe choosing a color would be desirable to you, if it's not to difficult to implement.

Thank you!

**Comment by yashpalgoyal1304** [comment] 2022-12-18 07:47
duplicate of #541

**Closed** 2022-12-19 09:36 UTC
Labels: feature
