### ISSUE TITLE
Bug or flash in dominosa

### ISSUE THREAD

**Issue by m5maxv** [chrisboyle/sgtpuzzles#571] opened 2022-10-24 13:15 UTC
In dominosa, we can use custom mode with dominos with number 10 or mode. Bug in the Side panel, se don't bave chose numbers (10 or more) to activate the coloris to help analysing the plate.

I was on a Chromecast at that time

**Comment by chrisboyle** [comment] 2022-10-24 14:07
Duplicate of #379, which also affects upstream. Unfortunately this cannot be straightforwardly improved on Android alone without complicating the merging of future changes. A decision must first be taken upstream about what the keyboard-based control scheme for numbers > 9 should be.

**Closed by chrisboyle** 2022-10-24 14:07 UTC
Labels: bug
