### ISSUE TITLE
In night mode certain highlight features are invisible and icons are barely visible

### ISSUE THREAD

**Issue by GamedevEmi** [chrisboyle/sgtpuzzles#586] opened 2023-01-19 22:03 UTC
**Describe the bug**
with night mode on, making highlights (such as selecting a square or using the note feature in undead and keen) are invisible against the dark background, previously they were gray (which was sufficiently visible). inputting values into a selected square shows the value correctly. In undead the monster icons show the outline but are filled in with the same color as the background, they are difficult to see

**To Reproduce**
Steps to reproduce the behavior: (this example will use Undead, but I have also found the issue in Keen and Filling)
1. Go to settings, turn on dark mode
2. Open Undead (at this point the undead icons at the top are hollow outlines)
3. Click any square to select it, click again to change to making notes (the lack of highlighting should be noticeable at this step)
4. Enter a value
5. See error

**Expected behavior**
The highlighted square should be a different color from the others and the undead icons should be colored in instead of camoflaged into the background.

**Screenshots**
![Screenshot_20230119-164713_Puzzles](https://user-images.githubusercontent.com/97924534/213571131-637b1f0b-22fc-4f53-97b3-891455105549.jpg)

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: Samsung galaxy s7 edge
 - Android version: 8.0.0
 - App version: 2023-01-17-2309-80f64cfc

**Additional context**
In night mode, Black Box and Galaxies look different but i'm not certain that those are unintended changes. I used the term 'invisible' to describe the issue, but the highlights may be hidden behind the background.

**Comment by chrisboyle** [comment] 2023-01-19 22:06
Hi, sorry, I just released a fix for this. You need a version starting 2023-01-18-... or newer.

(Duplicate of #585)

**Closed by chrisboyle** 2023-01-19 22:06 UTC
Labels: bug
