### ISSUE TITLE
Make game-size width-height swap for orientation optional

### ISSUE THREAD

**Issue by chtisgit** [chrisboyle/sgtpuzzles#389] opened 2016-04-26 16:21 UTC
When starting a custom game in Flip with width greater than height, the next time a
new game is initiated, width and height are flipped.

E.g.: Open Flip -> enter custom size width = 4, height = 8
-> solve the puzzle or hit "New game" -> you now get a map with width = 8 and height = 4

It doesn't flip the values a second time, but the values also appear flipped the next
time you open the "custom..." dialog.

**Comment by chrisboyle** [comment] 2016-04-26 16:33
The app changes the orientation to match that of your device at new-game time, because I used to get a lot of complaints, equally from phone and tablet users in either orientation, that some non-square presets, or their previously selected and remembered custom game size, did not make efficient use of space (or, that was what the complaints boiled down to).

It would be possible to make that behaviour optional and add a checkbox to Settings, or Settings/Advanced.

In any case I agree that perhaps a Toast is warranted to explain what has just happened (especially if it can then say that you can turn it off in Settings).

**Comment by chtisgit** [comment] 2016-04-26 16:36
Oh wow, that was a quick reply. Thanks for clarification!

**Comment by chrisboyle** [comment] 2016-07-08 07:26
Turns out I already had this request filed: duplicate of #365.

**Closed by chrisboyle** 2016-07-08 07:26 UTC
Labels: feature
