### ISSUE TITLE
Black box crash when showing solution on solved state

### ISSUE THREAD

**Issue by AndyPandy27** [chrisboyle/sgtpuzzles#651] opened 2024-03-14 00:42 UTC
**Describe the bug**
When selecting 'show solution'(not verify guesses) after solving a black box puzzle, the app returns to the puzzle select screen and resets the puzzle if it is selected again 

**To Reproduce**
1. Go to 'Black box
2. Solve the puzzle as normal, or use show solution and undo to get the solved puzzle
3. Select 'Show solution' in the menu
4. Puzzle crashes, resets and returns to puzzle select

**Expected behavior**
~~Shows 'Puzzle already solved' dialogue~~
To mirror the original website: Shows 'CORRECT' dialogue

**Version info (optional, but sometimes helpful)**
 - Phone/tablet model: Nokia TA-1128 (idk official name)
 - Android version: Android 11
 - App version : Version 2023-11-15-2237-96d65e85

**Comment by mquevill** [comment] 2024-03-14 01:16
This seems like a duplicate of #650, which has been fixed, but may not have rolled out to you yet. I can confirm that it is fixed in v2024-03-10-2312-80aac310 through the Play Store.

**Comment by chrisboyle** [comment] 2024-03-14 08:15
Yes, that'll be the same issue. The version with the fix is in beta, so there are three ways to get it, in increasing order of adventurousness:
* Wait a few days for the beta testers to confirm that nothing's broken in the update, at which point I'll roll it out to everyone
* Or [join beta testing](https://play.google.com/apps/testing/name.boyle.chris.sgtpuzzles) and wait "up to a few hours" for Google Play to offer you the update
* Or [get the APK directly](https://github.com/chrisboyle/sgtpuzzles/releases/download/2024-03-10-2312-80aac310/SGTPuzzles-2024-03-10-2312-80aac310.apk).

**Closed by chrisboyle** 2024-03-14 08:15 UTC
Labels: bug
