### ISSUE TITLE
Undead: countdown of the remaining undead people to be placed

### ISSUE THREAD

**Issue by asterbini** [chrisboyle/sgtpuzzles#241] opened 2015-01-06 00:19 UTC
It would be nice to have a config option: countdown
which would show the number of remaining un-placed vampires/ghosts/zombies

**Comment by chrisboyle** [comment] 2022-04-07 21:57
Duplicate of #245 (which was created later but mentions other games too).

**Closed by chrisboyle** 2022-04-07 21:57 UTC
Labels: feature, upstream
